name: Build APK

on:
push:
branches: [ "main" ]

jobs:
build:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v3

- name: Install
  run: |
    sudo apt update
    sudo apt install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk

- name: Python deps
  run: |
    pip install buildozer cython

- name: Init
  run: buildozer init

- name: Config
  run: |
    sed -i 's/title = .*/title = Bullet Knight/' buildozer.spec
    sed -i 's/package.name = .*/package.name = bulletknight/' buildozer.spec
    sed -i 's/requirements = .*/requirements = python3,kivy/' buildоzer.spec
    sed -i 's/source.include_exts = .*/source.include_exts = py,png,jpg,kv,atlas,wav,mp3,json/' buildozer.spec
    sed -i 's/orientation = .*/orientation = landscape/' buildozer.spec
    echo "android.permissions = INTERNET" >> buildozer.spec

- name: Build
  run: buildozer -v android debug

- name: Upload
  uses: actions/upload-artifact@v3
  with:
    name: apk
    path: bin/*.apk
